targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-agent
  logLevel: DEBUG
  # Disabling Kubelet verification for minikube
  kubelet:
    tlsVerify: false
  # Ignoring some problematic integrations on minikube
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager 
    - kube_scheduler 
  kubeStateMetricsEnabled: false