apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
      annotations:
        ad.datadoghq.com/my-container.check_names: '["filebeat"]'
        ad.datadoghq.com/my-container.init_configs: '[{}]'
        ad.datadoghq.com/my-container.instances: |
          [
            {
              "stats_endpoint": "%%host%%:2828/stats",
              "registry_file_path": "/var/lib/filebeat/registry",
              "port": "8080",
              "only_metrics": [
                "^filebeat", 
                "^publish\.events$"
              ]    
            }
          ]
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.5.3
        imagePullPolicy: Always