targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-agent
  processAgent:
    enabled: false
  kubelet:
    tlsVerify: false
  logLevel: DEBUG
  confd:
    traefik.yaml: |-
      ad_identifiers:
        - traefik
      init_config:
      instances:
        - host: "%%host%%"
          port: 8080
  kubeStateMetricsEnabled: false
agents:
  image: 
    name: traefik_agent
    tag: version1
    repository: docker.io/throatslasher/traefik_agent
    doNotCheckTag: true