targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-agent
  processAgent:
    enabled: false
  kubelet:
    tlsVerify: false
  logLevel: DEBUG
  kubeStateMetricsEnabled: false
agents:
  image: 
    name: fb-agent
    tag: v1
    repository: docker.io/throatslasher/fb-agent
    doNotCheckTag: true