targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-agent
  processAgent:
    enabled: false
  # Disabling Kubelet verification for minikube
  kubelet:
    tlsVerify: false
  # Ignoring some problematic integrations on minikube
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager 
    - kube_scheduler 
  logLevel: DEBUG
  kubeStateMetricsEnabled: false
agents:
  image: 
    name: fb-agent
    tag: v1
    repository: docker.io/throatslasher/fb-agent
    doNotCheckTag: true